[package]
name = "ntex-rust-template"
version = "0.1.0"
edition = "2021"
authors = ["ViniciosLugli <vinicioslugli@gmail.com>"]

[dependencies]
ntex = { version = "0.7.15", features = ["tokio"] }
env_logger = "0.10.1"