[package]
name = "ntex-rust-template"
version = "0.1.0"
edition = "2021"
authors = ["ViniciosLugli <vinicioslugli@gmail.com>"]

[dependencies]
ntex = { version = "2.0.0", features = ["tokio"] }
ntex-cors = "2.0.0"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
log = "0.4.21"
pretty_env_logger = "0.5.0"
dotenvy = "0.15.7"
